[package]
name = "poemguessr"
version = "0.1.0"
edition = "2024"

[dependencies]
axum = "0.8.9"
maud = "0.27.0"
thiserror = "2.0.20"
tokio = "1.53.1"
tower-http = { version = "0.7.0", features = ["trace"] }
tracing-subscriber = { version = "0.3.23", features = ["env-filter"] }
sqlx = { version = "0.9", features = [ "runtime-tokio", "sqlite" ] }
tracing = "0.1.44"
scraper = "0.27.0"
reqwest = "0.13.4"
url = "2.5.8"
markup5ever = "0.39.0"
itertools = "0.15.0"
